version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3000:3000"

  jsonserver:
    image: clue/json-server
    container_name: jsonserver
    volumes:
      - ./db.json:/data/db.json
      - ./routes.json:/data/routes.json
    entrypoint: ["json-server", "db.json", "-r", "routes.json"]
    ports:
      - "3000:3000"
